name: StaleBOT

on:
    workflow_dispatch:
    schedule:
        - cron: "30 14 * * *"

jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/stale@v3
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  days-before-stale: 7
                  days-before-close: 3
                  stale-issue-message: "This issue has been marked as stale due to inactivity and will be closed. Comment anything on this issue to prevent it"
                  stale-pr-message: "This pull request has been marked as stale due to inactivity and will be closed. Comment anything on this PR to prevent it"
                  exempt-issue-labels: "no-stale"
                  exempt-pr-labels: "no-stale"
